<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="AML_Investigation" duration-ms="1204" started-at="2019-05-29T05:34:59Z" finished-at="2019-05-29T05:35:00Z">
    <groups>
    </groups>
    <test name="POC_Execution" duration-ms="1204" started-at="2019-05-29T05:34:59Z" finished-at="2019-05-29T05:35:00Z">
      <class name="org.citi.runners.Runner_AMLInvestigation">
        <test-method status="PASS" signature="setUP()[pri:0, instance:org.citi.runners.Runner_AMLInvestigation@28d25987]" name="setUP" is-config="true" duration-ms="571" started-at="2019-05-29T11:04:59Z" finished-at="2019-05-29T11:04:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="RevPort(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:org.citi.runners.Runner_AMLInvestigation@28d25987]" name="RevPort" duration-ms="450" started-at="2019-05-29T11:04:59Z" description="RevPort" data-provider="features" finished-at="2019-05-29T11:05:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Different Accural Calculations]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at org.citi.runners.Runner_AMLInvestigation.RevPort(Runner_AMLInvestigation.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.citi.stepdefs.AMLInvestigations.TC001_Initial_StaticDataLoad.in_Security_Business_Work_Group(TC001_Initial_StaticDataLoad.java:15)
	at âœ½.Given Biller Group Member is logged in(TC001_Initial_StaticDataLoad.feature:7)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RevPort -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.citi.runners.Runner_AMLInvestigation@28d25987]" name="tearDown" is-config="true" duration-ms="27" started-at="2019-05-29T11:05:00Z" finished-at="2019-05-29T11:05:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.citi.runners.Runner_AMLInvestigation -->
    </test> <!-- POC_Execution -->
  </suite> <!-- AML_Investigation -->
</testng-results>
